apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xujt3w2xx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xujt3w2xx-go 
  name: xujt3w2xx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xujt3w2xx-go 
